---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nats.fullname" . }}-config
  namespace: {{ include "nats.namespace" . }}
  labels:
    {{- include "nats.labels" . | nindent 4 }}
data:
  {{- tpl (.Files.Glob "files/configmap/*").AsConfig . | nindent 2 }}
