# based on: https://github.com/helm/charts-repo-actions-demo/blob/main/.github/workflows/release.yaml
name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.0

      # using fork while awaiting merge of https://github.com/helm/chart-releaser/pull/151
      - name: Run chart-releaser
        uses: caleblloyd/helm-chart-releaser-action@v1.3.1
        with:
          charts_dir: helm/charts
          charts_repo_url: https://nats-io.github.io/k8s/helm/charts
          config: helm/cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
